[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 10000
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]
no_match_path = "test/kontrol/**"

[rpc_endpoints]
mainnet = "${RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 1024

[invariant]
runs = 256
depth = 32
